# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Camille Merose
email: hi.cam@merose.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello and welcome!
#baseurl: /foo # the subpath of your site, e.g. /blog
url: https://camille.merose.com # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.png
github_username:  camerose

#generate social links
social_link:
  github: camerose
  linkedin: camerose
  goodreads: camerose
  #email: hi.cam@merose.com
  spotify: l8o1pw0cfk5f2hzbgdektby4p
  smugmug: camillemerose

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num/"
show_excerpts: true
excerpt_length: 12 # words
hide_credits: true
