# top level stuff you probably don't need to touch
markdown: kramdown
icon: /assets/images/icon-512.png

#theme settings
theme: hitchens-theme
#hide_credits: true
#ignore_theme_config: true

#pagination settings
paginate: 10
plugins:
  - jekyll-paginate
paginate_path: "/page/:num/"

#post settings
#show_excerpts: true
#excerpt_length: 50 #words

#personal info
url: http://camillemerz.com
title: Camille Merz
description: >-
  Hello and welcome
baseurl: /
email: hi@camillemerz.com
github_username: camerz # username
#linkedin: cammerz
#google_analytics: UA-133683665-1

