# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://camillemerz.com
baseurl: /
title: Cam Merz
author: Cam Merz
description: Personal blog and resume
avatar: ProfilePhoto.jpg
email: hi@camillemerz.com
github: camerz # username
linkedin: cammerz
#stackoverflow: username   #e.g: users/2735833/proton1h1
google_analytics: UA-133683665-1


# needed for travis-ci build
exclude: [vendor]
